[project]
name = "bvolt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "influxdb-client>=1.49.0",
    "uvicorn>=0.40.0",
]
